### ISSUE TITLE
use the avatar dynamics system instead of particles

### ISSUE THREAD

**Issue by h3oCharles** [hfcRed/Among-Us-Follower#1]
currently, the follower uses the particle system. problem is, that can use 2 materials, or, in total, the prefab takes 3 materials before any customizations, is there any way to reduce this?

**Comment by hfcRed** [comment]
The whole point of this system is that it is self contained and not tied to an FX Layer. Contacts can only be used inside of the Avatars Playable Layers, so the installation would be more complex, could break avatars and wouldn't allow for having more than a single follower.

One of the particle systems has its renderer turned off so its not using any material, the total amount of materials of the prefab is therefore reduced to only two.

Followers that use contacts already exist and I recommend checking out the one by VRLabs if youre interested. 
https://github.com/VRLabs/Follower

But again, the setup is more complex and you're expected to make all the logic yourself. My package is aimed towards people that lack the abilities or are too lazy to set up more technically advanced followers by making it literally as easy as humanly possible to install, particle systems can not be avoided to achieve that goal.

**Comment by h3oCharles** [comment]
i think that's what i was looking for, thx
